name: scouting_app
description: Team 8873's scouting app for FRC 2024 Crescendo.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  build_runner: ^2.4.8
  file_picker: ^6.2.0
  flutter:
    sdk: flutter

  get_it: ^7.6.7
  network_info_plus: ^4.1.0+1
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  watch_it: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/biden.jpg
